version: "3.0"
services:
  nextjs:
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: Dockerfile
      image: nextjs-new:tag
    volumes:
      - ./:/var/nextjs/app
      - /var/nextjs/app/node_modules
      - /var/nextjs/app/.next
