version: "3.0"
services:
  nextjs:
    ports:
      - 3000:3000
    image: nextjs/vps:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
      
    volumes:
      - ./:/var/nextjs/app
      - /var/nextjs/app/node_modules
      - /var/nextjs/app/.next
